version: '2'
services:

  hamachi:
    image: "blacky/hamachi"
    container_name: hamachi
    hostname: hamachi
    restart: unless-stopped
    environment:
      - SAFEMODE=False
    privileged: true
    volumes:
      - ./data/hamachi/data:/data
    network_mode: "host"

  proxy:
    image: "blacky/proxy"
    container_name: proxy
    hostname: proxy
    restart: unless-stopped
    environment:
      - SAFEMODE=False
    volumes:
      - /mnt/md1:/mnt/md1
    ports:
      - "80:80"
      - "443:443"

  samba:
    image: "blacky/samba"
    container_name: samba
    hostname: samba
    restart: unless-stopped
    environment:
      - SAFEMODE=False
    volumes:
      - /mnt/md1:/mnt/md1
    ports:
      - "445:445"

  zeroconf:
    image: "blacky/zeroconf"
    container_name: zeroconf
    hostname: zeroconf
    restart: unless-stopped
    environment:
      - SAFEMODE=False
    privileged: true
    network_mode: "host"

  plex:
    image: "blacky/plex"
    container_name: plex
    hostname: plex
    restart: unless-stopped
    environment:
      - SAFEMODE=False
    volumes:
      - /mnt/md1:/mnt/md1
    ports:
      - "32400:32400"

  owncloud:
    image: "blacky/owncloud"
    container_name: owncloud
    hostname: owncloud
    restart: unless-stopped
    environment:
      - SAFEMODE=False
    volumes:
      - /mnt/md1:/mnt/md1
    ports:
      - "8080:80"
